export const SIGNUP_SHOW_ERROR = 'SIGNUP_SHOW_ERROR';
export const SIGNUP_SHOW_MESSAGE = 'SIGNUP_SHOW_MESSAGE';
export const SIGNUP_CLEAR_ERROR = 'SIGNUP_CLEAR_ERROR';
export const SIGNUP_CLEAR_MESSAGE = 'SIGNUP_CLEAR_MESSAGE';
export const SIGNUP_SET_LOADING = 'SIGNUP_SET_LOADING';
export const TOGGLE_SIGNUP_TIPS = 'TOGGLE_SIGNUP_TIPS';
export const SIGNUP_INVALIDATE_TIP = 'SIGNUP_INVALIDATE_TIP';
