export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR';
export const CREATE_EVENT_MESSAGE = 'CREATE_EVENT_MESSAGE';
export const CLEAR_CREATE_EVENT_ERROR = 'CLEAR_CREATE_EVENT_ERROR';
export const CLEAR_CREATE_EVENT_MESSAGE = 'CLEAR_CREATE_EVENT_MESSAGE';
export const CREATE_EVENT_ADD_GUEST = 'CREATE_EVENT_ADD_GUEST';
export const CREATE_EVENT_REMOVE_GUEST = 'CREATE_EVENT_REMOVE_GUEST';
