export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR';
export const CREATE_EVENT_MESSAGE = 'CREATE_EVENT_MESSAGE';
export const CLEAR_CREATE_EVENT_ERROR = 'CLEAR_CREATE_EVENT_ERROR';
export const CLEAR_CREATE_EVENT_MESSAGE = 'CLEAR_CREATE_EVENT_MESSAGE';
export const CREATE_EVENT_ADD_GUESTS = 'CREATE_EVENT_ADD_GUESTS';
export const CREATE_EVENT_SET_START_DATE_FOCUS = 'CREATE_EVENT_SET_START_DATE_FOCUS';
export const CREATE_EVENT_SET_END_DATE_FOCUS = 'CREATE_EVENT_SET_END_DATE_FOCUS';
