export const fields = {
  nameInput: {
    name: 'nameInput',
    value: '',
    initialValue: '',
    valid: false,
    invalid: true,
    dirty: false,
    pristine: true,
    error: 'value Required',
    active: false,
    touched: true,
    visited: true,
    autofilled: false,
  },
  emailInput: {
    name: 'emailInput',
    value: '',
    initialValue: '',
    valid: false,
    invalid: true,
    dirty: false,
    pristine: true,
    error: 'value Required',
    active: false,
    touched: false,
    visited: false,
    autofilled: false,
  },
  passwordInput: {
    name: 'passwordInput',
    value: '',
    initialValue: '',
    valid: false,
    invalid: true,
    dirty: false,
    pristine: true,
    error: 'value Required',
    active: false,
    touched: false,
    visited: false,
    autofilled: false,
  },
  passwordConfirmationInput: {
    name: 'passwordConfirmationInput',
    value: '',
    initialValue: '',
    valid: false,
    invalid: true,
    dirty: false,
    pristine: true,
    error: 'value Required',
    active: false,
    touched: false,
    visited: false,
    autofilled: false,
  },
  bioInput: {
    name: 'bioInput',
    value: '',
    initialValue: '',
    valid: true,
    invalid: false,
    dirty: false,
    pristine: true,
    active: false,
    touched: false,
    visited: false,
    autofilled: false,
  },
  employerInput: {
    name: 'employerInput',
    value: '',
    initialValue: '',
    valid: true,
    invalid: false,
    dirty: false,
    pristine: true,
    active: false,
    touched: false,
    visited: false,
    autofilled: false,
  },
};
