export const LOGIN_SHOW_ERROR = 'LOGIN_SHOW_ERROR';
export const LOGIN_SHOW_MESSAGE = 'LOGIN_SHOW_MESSAGE';
export const LOGIN_CLEAR_ERROR = 'LOGIN_CLEAR_ERROR';
export const LOGIN_CLEAR_MESSAGE = 'LOGIN_CLEAR_MESSAGE';
export const LOGIN_SET_LOADING = 'LOGIN_SET_LOADING';
