export const user = {
  nameInput: {
    name: 'nameInput',
    value: '',
    initialValue: '',
    valid: false,
    invalid: true,
    dirty: false,
    pristine: true,
    error: 'value Required',
    active: false,
    touched: true,
    visited: true,
    autofilled: false,
  },
  startDateInput: {
    name: 'startDateInput',
    value: '',
    initialValue: '',
    valid: false,
    invalid: true,
    dirty: false,
    pristine: true,
    error: 'value Required',
    active: false,
    touched: false,
    visited: false,
    autofilled: false,
  },
  endDateInput: {
    name: 'endDateInput',
    value: '',
    initialValue: '',
    valid: false,
    invalid: true,
    dirty: false,
    pristine: true,
    error: 'value Required',
    active: false,
    touched: false,
    visited: false,
    autofilled: false,
  },
  typeInput: {
    name: 'typeInput',
    value: '',
    initialValue: '',
    valid: false,
    invalid: true,
    dirty: false,
    pristine: true,
    error: 'value Required',
    active: false,
    touched: false,
    visited: false,
    autofilled: false,
  },
  hostInput: {
    name: 'hostInput',
    value: '',
    initialValue: '',
    valid: false,
    invalid: true,
    dirty: false,
    pristine: true,
    error: 'value Required',
    active: false,
    touched: false,
    visited: false,
    autofilled: false,
  },
  locationInput: {
    name: 'locationInput',
    value: '',
    initialValue: '',
    valid: false,
    invalid: true,
    dirty: false,
    pristine: true,
    error: 'value Required',
    active: false,
    touched: false,
    visited: false,
    autofilled: false,
  },
  guestsInput: {
    name: 'guestsInput',
    value: '',
    initialValue: '',
    valid: true,
    invalid: false,
    dirty: false,
    pristine: true,
    active: false,
    touched: false,
    visited: false,
    autofilled: false,
  },
  messageInput: {
    name: 'messageInput',
    value: '',
    initialValue: '',
    valid: true,
    invalid: false,
    dirty: false,
    pristine: true,
    active: false,
    touched: false,
    visited: false,
    autofilled: false,
  },
};

export const mockFn = (e) => e;
